sudo: required
services:
  - docker

before_install:
  - docker build -t test -f ./client/Dockerfile.dev ./client

script:
  - docker run test npm test -- --coverage

after_success:
  - docker build -t 1942/multi-client ./client
  - docker build -t 1942/multi-nginx ./nginx
  - docker build -t 1942/multi-server ./server
  - docker build -t 1942/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push 1942/multi-client
  - docker push 1942/multi-nginx
  - docker push 1942/multi-server
  - docker push 1942/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-649086133323
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
